
import { Rubik ,Open_Sans } from 'next/font/google'
const opem_sans = Open_Sans({ subsets: ['latin'] })


const metadata = {
  title: 'My Site',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opem_sans.className}>{children}</body>
    </html>
  )
}
